platform :ios, '7.0'
pod 'SZTextView'
pod "AFNetworking", "~> 2.5.3"
pod 'Reachability', '~> 3.2'
pod 'SDWebImage', '3.7.2'
pod 'Masonry','0.6.0'
pod 'KNSemiModalViewController'
pod 'AVOSCloud'
pod 'MJRefresh'
pod 'CocoaAsyncSocket'
pod 'FlickerNumber'
pod 'MBProgressHUD'
pod 'JDStatusBarNotification'
pod 'TPKeyboardAvoiding'
pod 'DateTools'
